/* ==========================================================================
   tools/gen-recipes.js  —  build js/recipes-data.js from the official dump.

   Usage:  node tools/gen-recipes.js <path-to-items.json>

   Extracts exact crafting requirements (materials, counts, focus cost, and
   amount produced) for standard weapons, armour, off-hands, tools, food and
   potions. Artifact / faction / avalonian variants are skipped so the tables
   stay to the plain craftable economy. Output is a compact tuple map:

     AO.RECIPE_DATA[resultId] = [category, tier, enchant, focus, yield, mats]
       mats = [[materialId, count], ...]
   ========================================================================== */
'use strict';
const fs = require('fs');
const path = require('path');

const srcPath = process.argv[2];
if (!srcPath) { console.error('Pass the path to items.json'); process.exit(1); }
const j = JSON.parse(fs.readFileSync(srcPath, 'utf8'));
const root = j.items;

const MELEE = new Set(['sword', 'axe', 'mace', 'hammer', 'spear', 'dagger', 'quarterstaff', 'knuckles']);
const RANGED = new Set(['bow', 'crossbow']);
const MAGIC = new Set(['firestaff', 'holystaff', 'arcanestaff', 'froststaff', 'cursestaff', 'naturestaff']);

function weaponCategory(cc) {
  if (cc === 'tools') return 'TOOL';
  if (MELEE.has(cc)) return 'MELEE';
  if (RANGED.has(cc)) return 'RANGED';
  if (MAGIC.has(cc)) return 'MAGIC';
  return null;
}
function equipCategory(cc) {
  if (cc && cc.indexOf('plate') === 0) return 'PLATE';
  if (cc && cc.indexOf('leather') === 0) return 'LEATHER_ARMOR';
  if (cc && cc.indexOf('cloth') === 0) return 'CLOTH_ARMOR';
  if (cc === 'bag' || cc === 'cape' || cc === 'offhand') return 'OFFHAND';
  // gatherergear (harvester outfits) is intentionally skipped: niche, and it
  // would triple the Tools category. Only the 5 gathering tools (weapon dump,
  // craftingcategory "tools") are surfaced.
  return null;
}

var MAX_ENCHANT = 3; // .4 overcharge items barely trade; skip to trim scope

function asArray(v) { return v == null ? [] : (Array.isArray(v) ? v : [v]); }
function tierOf(id) { const m = /^T(\d)/.exec(id); return m ? +m[1] : 0; }

// A material id as the price API expects it: enchanted resources carry @level.
function matId(res) {
  const lvl = +(res['@enchantmentlevel'] || 0);
  const id = res['@uniquename'];
  return lvl > 0 ? id + '@' + lvl : id;
}

// Skip artifact / soul / relic / token inputs -> not part of the plain economy.
const SKIP_MAT = /ARTEFACT|SOUL|RELIC|TOKEN|QUESTITEM|SKILLBOOK/;

function readReqs(reqNode) {
  const req = asArray(reqNode)[0];
  if (!req) return null;
  const mats = asArray(req.craftresource).map(function (r) { return [matId(r), +r['@count']]; });
  if (!mats.length) return null;
  if (mats.some(function (m) { return SKIP_MAT.test(m[0]); })) return null;
  return { mats: mats, focus: +(req['@craftingfocus'] || 0), yield: +(req['@amountcrafted'] || 1) };
}

const DATA = {};
let count = 0, enchCount = 0;

function addItem(item, category) {
  const base = item['@uniquename'];
  if (!category) return;
  const tier = +(item['@tier'] || tierOf(base));

  const b = readReqs(item.craftingrequirements);
  if (b) {
    DATA[base] = [category, tier, 0, b.focus, b.yield, b.mats];
    count++;
  }
  // enchant variants
  asArray(item.enchantments && item.enchantments.enchantment).forEach(function (e) {
    const lvl = +e['@enchantmentlevel'];
    const r = readReqs(e.craftingrequirements);
    if (r && lvl > 0 && lvl <= MAX_ENCHANT) {
      DATA[base + '@' + lvl] = [category, tier, lvl, r.focus, r.yield, r.mats];
      enchCount++;
    }
  });
}

// ---- weapons -------------------------------------------------------------
asArray(root.weapon).forEach(function (w) {
  const cat = weaponCategory(w['@craftingcategory']);
  addItem(w, cat);
});

// ---- armour / off-hands / tools -----------------------------------------
asArray(root.equipmentitem).forEach(function (e) {
  const cat = equipCategory(e['@craftingcategory']);
  // capes: keep only the plain city-less cape to avoid 15 faction variants
  const id = e['@uniquename'];
  if (cat === 'OFFHAND' && /CAPE/.test(id) && !/^T\d_CAPE$/.test(id)) return;
  addItem(e, cat);
});

// ---- food & potions ------------------------------------------------------
asArray(root.consumableitem).forEach(function (c) {
  const id = c['@uniquename'];
  let cat = null;
  if (/_MEAL_/.test(id)) cat = 'FOOD';
  else if (/_POTION_/.test(id)) cat = 'POTION';
  if (!cat) return;
  if (/_AVALON/.test(id)) return; // avalonian meals use special inputs
  addItem(c, cat);
});

// ---- write ---------------------------------------------------------------
const header =
  '/* AUTO-GENERATED by tools/gen-recipes.js from the official ao-bin-dumps.\n' +
  '   Do not edit by hand — regenerate instead.\n' +
  '   Shape: AO.RECIPE_DATA[id] = [category, tier, enchant, focus, yield, [[matId,count]...]] */\n';
const body = '(function(AO){AO.RECIPE_DATA=' + JSON.stringify(DATA) + ';}(window.AO=window.AO||{}));\n';
const outPath = path.join(__dirname, '..', 'js', 'recipes-data.js');
fs.writeFileSync(outPath, header + body);

const bytes = fs.statSync(outPath).size;
console.log('base recipes : ' + count);
console.log('enchant rows : ' + enchCount);
console.log('total keys   : ' + Object.keys(DATA).length);
console.log('output       : ' + outPath + '  (' + (bytes / 1024).toFixed(0) + ' KB)');

// quick sanity print
['T5_2H_FROSTSTAFF', 'T4_POTION_HEAL', 'T5_MEAL_STEW', 'T4_HEAD_PLATE_SET1'].forEach(function (id) {
  console.log('  ' + id + ' = ' + JSON.stringify(DATA[id]));
});
